const WORD_PAIRS = [
  { word: "Knife", hint: "Edge" },
  { word: "Clock", hint: "Ticks" },
  { word: "River", hint: "Current" },
  { word: "Mirror", hint: "Reflection" },
  { word: "Key", hint: "Access" },
  { word: "Bridge", hint: "Crossing" },
  { word: "Fire", hint: "Heat" },
  { word: "Snow", hint: "Silent" },
  { word: "Book", hint: "Spine" },
  { word: "Camera", hint: "Focus" },

  { word: "Pillow", hint: "Rest" },
  { word: "Shoes", hint: "Sole" },
  { word: "Tree", hint: "Roots" },
  { word: "Phone", hint: "Signal" },
  { word: "Bottle", hint: "Cap" },
  { word: "Window", hint: "Pane" },
  { word: "Door", hint: "Hinge" },
  { word: "Mountain", hint: "Peak" },
  { word: "Beach", hint: "Shore" },
  { word: "Pen", hint: "Ink" },

  { word: "Wallet", hint: "Fold" },
  { word: "Train", hint: "Track" },
  { word: "Plane", hint: "Altitude" },
  { word: "Ring", hint: "Band" },
  { word: "Chair", hint: "Legs" },
  { word: "Table", hint: "Surface" },
  { word: "Glasses", hint: "Lens" },
  { word: "Hat", hint: "Brim" },
  { word: "Rain", hint: "Drizzle" },
  { word: "Sun", hint: "Glare" },

  { word: "Moon", hint: "Phase" },
  { word: "Star", hint: "Twinkle" },
  { word: "Ocean", hint: "Depth" },
  { word: "Island", hint: "Isolated" },
  { word: "Forest", hint: "Canopy" },
  { word: "Candle", hint: "Wick" },
  { word: "Bell", hint: "Chime" },
  { word: "Drum", hint: "Beat" },
  { word: "Guitar", hint: "Strings" },
  { word: "Piano", hint: "Keys" },

  { word: "Backpack", hint: "Strap" },
  { word: "Suitcase", hint: "Handle" },
  { word: "Map", hint: "Scale" },
  { word: "Compass", hint: "North" },
  { word: "Lighthouse", hint: "Beacon" },
  { word: "Anchor", hint: "Weight" },
  { word: "Helmet", hint: "Shell" },
  { word: "Shield", hint: "Block" },
  { word: "Sword", hint: "Blade" },
  { word: "Crown", hint: "Throne" }
];
